//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.03 at 08:30:13 AM ICT 
//


package com.viettel.vds.springexample.soap.edm;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ref" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="res"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="code" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="util"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="addr" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="taxRef" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *                 &lt;attribute name="distId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="tariff" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="stdToken"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *                 &lt;attribute name="amt" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *                 &lt;attribute name="tax" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *                 &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="rctNum" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="customerMsg" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="supGrpRef" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="term" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="seqNum" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ref",
    "res",
    "util",
    "tariff",
    "stdToken",
    "customerMsg"
})
@XmlRootElement(name = "vendRes")
public class VendRes {

    @XmlElement(required = true)
    protected String ref;
    @XmlElement(required = true)
    protected VendRes.Res res;
    @XmlElement(required = true)
    protected VendRes.Util util;
    @XmlElement(required = true)
    protected String tariff;
    @XmlElement(required = true)
    protected VendRes.StdToken stdToken;
    @XmlElement(required = true)
    protected String customerMsg;
    @XmlAttribute(name = "supGrpRef")
    protected Integer supGrpRef;
    @XmlAttribute(name = "term")
    protected String term;
    @XmlAttribute(name = "seqNum")
    protected Integer seqNum;
    @XmlAttribute(name = "time")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar time;

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRef(String value) {
        this.ref = value;
    }

    /**
     * Gets the value of the res property.
     * 
     * @return
     *     possible object is
     *     {@link VendRes.Res }
     *     
     */
    public VendRes.Res getRes() {
        return res;
    }

    /**
     * Sets the value of the res property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendRes.Res }
     *     
     */
    public void setRes(VendRes.Res value) {
        this.res = value;
    }

    /**
     * Gets the value of the util property.
     * 
     * @return
     *     possible object is
     *     {@link VendRes.Util }
     *     
     */
    public VendRes.Util getUtil() {
        return util;
    }

    /**
     * Sets the value of the util property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendRes.Util }
     *     
     */
    public void setUtil(VendRes.Util value) {
        this.util = value;
    }

    /**
     * Gets the value of the tariff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTariff() {
        return tariff;
    }

    /**
     * Sets the value of the tariff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTariff(String value) {
        this.tariff = value;
    }

    /**
     * Gets the value of the stdToken property.
     * 
     * @return
     *     possible object is
     *     {@link VendRes.StdToken }
     *     
     */
    public VendRes.StdToken getStdToken() {
        return stdToken;
    }

    /**
     * Sets the value of the stdToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendRes.StdToken }
     *     
     */
    public void setStdToken(VendRes.StdToken value) {
        this.stdToken = value;
    }

    /**
     * Gets the value of the customerMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerMsg() {
        return customerMsg;
    }

    /**
     * Sets the value of the customerMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerMsg(String value) {
        this.customerMsg = value;
    }

    /**
     * Gets the value of the supGrpRef property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSupGrpRef() {
        return supGrpRef;
    }

    /**
     * Sets the value of the supGrpRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSupGrpRef(Integer value) {
        this.supGrpRef = value;
    }

    /**
     * Gets the value of the term property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerm() {
        return term;
    }

    /**
     * Sets the value of the term property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerm(String value) {
        this.term = value;
    }

    /**
     * Gets the value of the seqNum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSeqNum() {
        return seqNum;
    }

    /**
     * Sets the value of the seqNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSeqNum(Integer value) {
        this.seqNum = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime(XMLGregorianCalendar value) {
        this.time = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="code" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Res {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "code", required = true)
        protected String code;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
     *       &lt;attribute name="amt" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
     *       &lt;attribute name="tax" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
     *       &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="rctNum" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class StdToken {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "units")
        protected Double units;
        @XmlAttribute(name = "amt")
        protected BigDecimal amt;
        @XmlAttribute(name = "tax")
        protected BigDecimal tax;
        @XmlAttribute(name = "desc")
        protected String desc;
        @XmlAttribute(name = "rctNum")
        protected String rctNum;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the units property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getUnits() {
            return units;
        }

        /**
         * Sets the value of the units property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setUnits(Double value) {
            this.units = value;
        }

        /**
         * Gets the value of the amt property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAmt() {
            return amt;
        }

        /**
         * Sets the value of the amt property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAmt(BigDecimal value) {
            this.amt = value;
        }

        /**
         * Gets the value of the tax property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTax() {
            return tax;
        }

        /**
         * Sets the value of the tax property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTax(BigDecimal value) {
            this.tax = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

        /**
         * Gets the value of the rctNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRctNum() {
            return rctNum;
        }

        /**
         * Sets the value of the rctNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRctNum(String value) {
            this.rctNum = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="addr" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="taxRef" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
     *       &lt;attribute name="distId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Util {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "addr")
        protected String addr;
        @XmlAttribute(name = "taxRef")
        protected Long taxRef;
        @XmlAttribute(name = "distId")
        protected String distId;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the addr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddr() {
            return addr;
        }

        /**
         * Sets the value of the addr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddr(String value) {
            this.addr = value;
        }

        /**
         * Gets the value of the taxRef property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getTaxRef() {
            return taxRef;
        }

        /**
         * Sets the value of the taxRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setTaxRef(Long value) {
            this.taxRef = value;
        }

        /**
         * Gets the value of the distId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDistId() {
            return distId;
        }

        /**
         * Sets the value of the distId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDistId(String value) {
            this.distId = value;
        }

    }

}
